# Generated by Django 5.0.4 on 2024-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='count_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='catalog/articles/default.jpg', null=True,
                                    upload_to='catalog/articles/', verbose_name='Превью статьи'),
        ),
    ]
