# Generated by Django 5.0.5 on 2024-05-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_articles_count_views_alter_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='count_views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='journal/articles/default.jpg', null=True, upload_to='journal/articles/', verbose_name='Превью статьи'),
        ),
    ]
